# 适用于 OpenSumi core 仓库的正式版本发布流程

name: Release

on:

  # 在 Release Issue 评论特定内容后执行
  issue_comment:
    events: [created]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issue_comment' &&
      (
        github.event.issue.author_association == 'MEMBER' ||
        github.event.issue.author_association == 'OWNER' ||
        github.event.issue.author_association == 'CONTRIBUTOR'
      ) &&
      ((contains(github.event.issue.body, 'Release Summary') &&
        contains(github.event.issue.title,'OpenSumi Release')) &&
        startsWith(github.event.comment.body, '/release')) &&
      contains(github.event.issue.labels.*.name, 'release')

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - name: Set Current Version
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV

      - uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        env:
          TAG: v${{env.CURRENT_VERSION}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Git Identity
        if: steps.checkTag.outputs.exists == 'false'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 安装依赖并构建
      - name: Install dependencies & Build
        if: steps.checkTag.outputs.exists == 'false'
        run: |
          npm i
          npm run init

      # 生成 Changelog, 会将内容写入到 ./releaselog.md 中
      - name: Create release log
        if: steps.checkTag.outputs.exists == 'false'
        id: release-log
        run: |
          npm run changelog -- --remote
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 更新 Changelog 到 release issue 正文
      - name: Update prerelease changelog for current issue
        if: steps.checkTag.outputs.exists == 'false'
        uses: actions/github-script@v4
        id: changelog
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          # JavaScript
          script: |
            const fs = require('fs');
            const releasemd = fs.readFileSync('./releaselog.md', 'utf8').toString();
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `🤖 OpenSumi Release v${process.env.CURRENT_VERSION} - ${new Date().toDateString()}`,
              body: `## v${process.env.CURRENT_VERSION} Release Summary \r\n ${releasemd}`
            });
            return releasemd;

      # 发布正式版本
      - name: Publish prod version
        if: steps.checkTag.outputs.exists == 'false'
        run: |
          lerna publish --exact ${{env.CURRENT_VERSION}} --dist-tag latest --force-publish='*' --ignore-prepublish --ignore-scripts --no-private -y
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git Tag
        if: steps.checkTag.outputs.exists == 'false'
        uses: pkgdeps/git-tag-action@v2
        with:
          version: ${{ env.CURRENT_VERSION }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Create Release
        id: create_release
        if: steps.checkTag.outputs.exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          release_name: OpenSumi Release v${{ env.CURRENT_VERSION }}
          body: |
            ${{steps.changelog.outputs.result}}
          draft: false
          prerelease: false

      - uses: actions/github-script@v4
        if: steps.checkTag.outputs.exists == 'false'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueBody =
              '🎉 New release version ' +
              process.env.CURRENT_VERSION +
              ' publish successful! You can install release version via `npm install package@' +
              process.env.CURRENT_VERSION;

            // 在 issue 中通知版本已发布完，并附带版本号
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueBody,
            });

            // 关闭 issue
            github.issues.update({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed'
            });

            // 锁定 issue
            github.issues.lock({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              lock_reason: 'resolved',
            });

      - uses: actions/github-script@v4
        if: steps.checkTag.outputs.exists == 'true'
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issueBody =
              '❌ Sorry, v' +
              process.env.CURRENT_VERSION +
              ' is already existed! please update your lerna.json and try again.';
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: issueBody
            })
